### ISSUE TITLE
non-straight edge

### ISSUE THREAD

**Issue by Hoonly** [emx77/ASI_MTF#1]
Thank you for the convenient tools. I wonder if there are some references about details of these two MTF methods, especially explanation for the mentioned ‘The edge does not have to be straight’ in README.

**Comment by emx77** [comment]
The program processes each row individually of the region of interest. For each row it estimates the edge position by fitting a Gaussian on the differentials (pixel to pixel slopes). This row's edge position is then the reference for the current row. It is important to have sufficient sampling at different points within one pixel. This requires data from multiple rows. Even with a non perfect straight edge sufficient pixel sampling can be achieved in many cases.  
Some background information on edge functions/psfs/MTFs can be found in section 3 of https://www.sciencedirect.com/science/article/pii/S0304399109001120
The idea to get a reference point per row is something I thought of myself, however maybe other programs also use this procedure.
