### ISSUE TITLE
The results calculated by ASI_MTF and Imtest  are different 

### ISSUE THREAD

**Issue by Springder** [emx77/ASI_MTF#2]
I  want use slant edge to calculate MTF in Nyquist frequency by ASI_MTF and Imtest, and then I find the results calculated by these tools are different. 
 Have you ever done something like that？ I want to know why?

**Comment by emx77** [comment]
Some comparisons to other MTF calculation have been done and the results seem to be so far similar.
The results ASI_MTF shows are in spatial frequency as fraction of the Nyquist frequency, that is 1/(2*pixel pitch).
I have seen that sometimes people use the plain spatial frequency or scale it to line pairs per mm. That could be a source of confusion.

**Comment by Springder** [comment]
Whatever way they express spatial frequencies, the MTF value at Nyquist frequency should be close. 
But I used the same slant edge(5 °) to calculate MTF value in at Nyquist frequency by ASI_MTF and Imatest, the calculation result of the former is 0.5098, another is 0.117.  I wonder how different they are.

![IMatestresult](https://user-images.githubusercontent.com/25104564/117235810-0b037e00-ae5a-11eb-989e-80365964c772.png)

**Comment by Springder** [comment]
![ASI_MTFresult](https://user-images.githubusercontent.com/25104564/117236164-c4625380-ae5a-11eb-8838-a5323cef7e66.png)

**Comment by emx77** [comment]
Dear Michael,
Thank you sharing this comparison.  
I do not know exactly why the results at MTF(Nyquist) are about a factor 2 different in this case. 
It might be related how the sigma or RMS of the point spread function (derivative of the edge spread function) is calculated. 
Small changes in this value have a strong effect on the MTF at the higher spatial frequencies. To understand this better it would be required to do a detailed step by step check of the two different programs.
Kind regards, Erik.
