### ISSUE TITLE
'Ideal' curve

### ISSUE THREAD

**Issue by MarnixMeersman** [emx77/ASI_MTF#3]
Hi thank you for this plugin. 
I see that the latest MTF plugin also return an 'ideal' curve. I was wondering if there is any literature on what this curve labeled 'ideal' is. 

Thanks

**Comment by emx77** [comment]
Hi, For the MTF calculations I make use of the methods described in https://doi.org/10.1016/j.ultramic.2009.04.002. An ideal or perfect 2D pixel detector does not have any blurring effects.  Kind regards
